version: '3.7'
services:
  php-fpm:
    build: ./images/php
    volumes:
      - type: bind
        source: ./www
        target: /var/www/
    ports:
      - "9000:9000"
  nginx:
    build: ./images/nginx
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    ports:
      - "80:80"
  mariadb-dev:
    build: ./images/mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: password
  mariadb-test:
    build: ./images/mariadb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password